=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/common_1_0/pattern_1_0.dtd
<?xml version="1.0" encoding="US-ASCII"?>

<!-- This dtd is used for validating the Pattern Templates, utitlised by the Pattern Generator, for generating the various components of a Pattern -->

<!ELEMENT BuildPattern (Name,PreRequesites,Components)>
<!ELEMENT Name (#PCDATA)>

<!ELEMENT PreRequesites (Class*)>
<!ELEMENT Class (#PCDATA)>

<!ELEMENT Components (Build+)>
<!ELEMENT Build (Template,Package,FileName,Override,Generate?)>
<!ELEMENT Template (#PCDATA)>
<!ELEMENT Package (#PCDATA)>
<!ELEMENT FileName (#PCDATA)>
<!ELEMENT Override (#PCDATA)>
<!ELEMENT Generate (Type,ClassName?,Arguments?,WorkingDirectory?,CommandLine?)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT ClassName (#PCDATA)>
<!ELEMENT Arguments (#PCDATA)>
<!ELEMENT WorkingDirectory (#PCDATA)>
<!ELEMENT CommandLine (#PCDATA)>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/script_generator_1_0/SecurityDomainPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>CreatPackagePattern</Name>

    <PreRequesites>
    </PreRequesites>

    <Components>
        <Build>
            <Template>patterns/library/script_generator_1_0/CreatePredicate.wm</Template>
            <Package>java.$(MappingPackage.Lower)</Package>
            <FileName>$(BasePackage)_CreatePredicate.sql</FileName>
            <Override>True</Override>
        </Build>
        <Build>
            <Template>patterns/library/script_generator_1_0/DropPredicate.wm</Template>
            <Package>java.$(MappingPackage.Lower)</Package>
            <FileName>$(BasePackage)_DropPredicate.sql</FileName>
            <Override>True</Override>
        </Build>
        <Build>
            <Template>patterns/library/script_generator_1_0/ApplyPredicate.wm</Template>
            <Package>java.$(MappingPackage.Lower)</Package>
            <FileName>$(BasePackage)_ApplyPredicate.sql</FileName>
            <Override>True</Override>
        </Build>

    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/domain_creator_1_0/DomainCreatorPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>DomainCreatorPattern</Name>

    <PreRequesites>
    </PreRequesites>

    <Components>
        <Build>
            <Template>patterns/library/domain_creator_1_0/DomainObject.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1).java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/domain_creator_1_0/MetaObject.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1)Meta.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/domain_creator_1_0/Resources.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1)Resources.properties</FileName>
            <Override>Merge</Override>
        </Build>
        
        <Build>
            <Template>patterns/library/domain_creator_1_0/Mapping.wm</Template>
            <Package>java.$(MappingPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1).xml</FileName>
            <Override>True</Override>
        </Build>

        <!-- uncomment to generate Configuration classes -->
        <!--<Build>-->
            <!--<Template>patterns/library/domain_creator_1_1/DomainConfig.wm</Template>-->
            <!--<Package>java.$(DomainPackage.Lower)</Package>-->
            <!--<FileName>$(DomainObject.Upper1)Config.java</FileName>-->
            <!--<Override>False</Override>-->
        <!--</Build>-->

        <!-- uncomment to build for Oracle SQL Scripts -->
        <Build>
            <Template>patterns/library/domain_creator_1_0/CreateTable.wm</Template>
            <Package>sql/create-table-scripts/oracle</Package>
            <FileName>$(DatabaseTable.Upper).sql</FileName>
            <Override>True</Override>
        </Build>
        <!-- end -->
        
        <!-- uncomment to build for MSSQL Scripts -->
        <Build>
            <Template>patterns/library/domain_creator_1_0/CreateTableMSSQL.wm</Template>
            <Package>sql/create-table-scripts/mssqlserver</Package>
            <FileName>$(DatabaseTable.Upper).sql</FileName>
            <Override>True</Override>
        </Build>
        <!-- end -->
        
        <!-- uncomment to build for MySQL Scripts -->
        <Build>
            <Template>patterns/library/domain_creator_1_0/CreateTableMySQL.wm</Template>
            <Package>sql/create-table-scripts/mysql</Package>
            <FileName>$(DatabaseTable.Upper).sql</FileName>
            <Override>True</Override>
        </Build>
        <!-- end -->
        
    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/object_viewer_1_0/ObjectViewerPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>ObjectViewerPattern</Name>

    <PreRequesites>
    </PreRequesites>
    
    <Components>
        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentViewerInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)InDto.java</FileName>
            <Override>Merge</Override>
        </Build>


#if ($RelatedObjects != null) #begin
#foreach $object in $RelatedObjects.values() #begin
        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentViewerRelatedOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(object.ObjectName.Upper1)Dto.java</FileName>
            <Override>Merge</Override>
        </Build>

#end
#end
        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentViewerOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)OutDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_viewer_1_0/IComponent.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>I$(Component.Upper1).java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentTx.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).tx</Package>
            <FileName>$(Component.Upper1)Tx.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentController.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Component.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentForm.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Form.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentAction.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Action.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower).jsp</Package>
            <FileName>view.jsp</FileName>
            <Override>False</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentDefinitionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentDefinition.xfragment</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentStrutsFormBeanXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigFormBean.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentStrutsGlobalForwardXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigGlobalForward.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_viewer_1_0/ComponentStrutsActionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigAction.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_viewer_1_0/ApplicationResources.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ApplicationResources.properties</FileName>
            <Override>True</Override>
        </Build>
    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/object_maintenance_1_0/ObjectMaintenancePattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>ObjectMaintenancePattern</Name>

    <PreRequesites>
    </PreRequesites>
    
    <Components>
        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentCreateInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)CreateInDto.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentCreateOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)CreateOutDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentRetrieveInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)RetrieveInDto.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentRetrieveOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)RetrieveOutDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentUpdateInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)UpdateInDto.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentDeleteInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)DeleteInDto.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/IComponent.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>I$(Component.Upper1).java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentTx.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).tx</Package>
            <FileName>$(Component.Upper1)Tx.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentController.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Component.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentForm.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Form.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentAction.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Action.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower).jsp</Package>
            <FileName>maintenance.jsp</FileName>
            <Override>False</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentDefinitionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentDefinition.xfragment</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentStrutsFormBeanXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigFormBean.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentStrutsGlobalForwardXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigGlobalForward.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_1_0/ComponentStrutsActionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigAction.xfragment</FileName>
            <Override>True</Override>
        </Build>
    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/object_maintenance_2_0/ObjectMaintenancePattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>ObjectMaintenancePattern</Name>

    <PreRequesites>
    </PreRequesites>
    
    <Components>
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentCreateInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)CreateInDto.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentRetrieveInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)RetrieveInDto.java</FileName>
            <Override>Merge</Override>
        </Build>


#if ($RelatedObjects != null) #begin
#foreach $object in $RelatedObjects.values() #begin
#if ($object.RelationshipToDomainObject.RelationshipTypeMany && $object.RelatedObjectFields != null) #begin
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentRelatedOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(object.Name.Upper1)Dto.java</FileName>
            <Override>Merge</Override>
        </Build>

#end
#end
#end
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentRetrieveOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)RetrieveOutDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentUpdateInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)UpdateInDto.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentDeleteInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)DeleteInDto.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentPrevalidateOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)PrevalidateOutDto.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_2_0/IComponent.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>I$(Component.Upper1).java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentTx.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).tx</Package>
            <FileName>$(Component.Upper1)Tx.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentController.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Component.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentForm.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Form.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentAction.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Action.java</FileName>
            <Override>Merge</Override>
        </Build>


#foreach $screen in $Screens.values() #begin
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower)</Package>
            <FileName>$(screen.Name.Lower1).jsp</FileName>
            <Override>OverrideIfMarkerPresentOrCreateTempFileIfMarkerAbsent</Override>
        </Build>
#end
    
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentDefinitionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentDefinition.xfragment</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentStrutsFormBeanXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigFormBean.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentStrutsGlobalForwardXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigGlobalForward.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentStrutsActionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigAction.xfragment</FileName>
            <Override>True</Override>
        </Build>
        
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentTilesDefinitions.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentTilesDefinitions.xfragment</FileName>
            <Override>False</Override>
        </Build>
        
        <Build>
            <Template>patterns/library/object_maintenance_2_0/ComponentDefaultValues.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentDefaultValues.properties</FileName>
            <Override>False</Override>
        </Build>
    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/domain_creator_with_jpa_1_0/DomainCreatorEventTransaction.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>DomainCreatorPattern</Name>

    <PreRequesites>
    </PreRequesites>

    <Components>

        <!-- generate the model with no lifecycle events -->
        <Build>
            <Template>patterns/library/domain_creator_with_jpa_1_0/DomainObjectNoRINoLifecycleEvents.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1).java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/domain_creator_1_1/MetaObject.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1)Meta.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/domain_creator_1_1/Resources.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1)Resources.properties</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/domain_creator_1_1/Mapping.wm</Template>
            <Package>java.$(MappingPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1).xml</FileName>
            <Override>True</Override>
        </Build>

        <!-- uncomment to build for Oracle SQL Scripts -->
        <Build>
            <Template>patterns/library/domain_creator_1_1/CreateTable.wm</Template>
            <Package>sql/install/oracle/tables</Package>
            <FileName>$(DatabaseTable.Upper).sql</FileName>
            <Override>True</Override>
        </Build>
        <!-- end -->

        <!-- For SEPARATE Constraint Script -->
        <Build>
            <Template>patterns/library/domain_creator_1_1/CreateConstraint.wm</Template>
            <Package>sql/install/oracle/constraints</Package>
            <FileName>$(DatabaseTable.Upper).sql</FileName>
            <Override>True</Override>
        </Build>
        <!-- end -->

        <!-- uncomment to build for MSSQL Scripts -->
        <Build>
            <Template>patterns/library/domain_creator_1_1/CreateTableMSSQL.wm</Template>
            <Package>sql/install/mssqlserver/tables</Package>
            <FileName>$(DatabaseTable.Upper).sql</FileName>
            <Override>True</Override>
        </Build>
        <!-- end -->

        <!-- uncomment to build for MySQL Scripts -->
        <Build>
            <Template>patterns/library/domain_creator_1_1/CreateTableMySQL.wm</Template>
            <Package>sql/install/mysql/tables</Package>
            <FileName>$(DatabaseTable.Upper).sql</FileName>
            <Override>True</Override>
        </Build>
        <!-- end -->

        <!-- create new AOP fragment to represent the meta data -->
        <Build>
            <Template>patterns/library/domain_creator_1_1/MetaAop.wm</Template>
            <Package>aop/1/domain</Package>
            <FileName>$(DomainObject.Upper1)-aop.xml</FileName>
            <Override>True</Override>
        </Build>

    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/stored_procedure_creator_1_0/StoredProcedureCreatorPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
  <Name>StoredProcedureCreatorPattern</Name>

  <PreRequesites>
  </PreRequesites>
    
  <Components>
    <Build>
      <Template>patterns/library/stored_procedure_creator_1_0/StoredProcedure.wm</Template>
      <Package>java.$(StoredProcedurePackage.Lower)</Package>
      <FileName>$(StoredProcedure.Upper1).java</FileName>
      <Override>Merge</Override>
    </Build>

    <Build>
      <Template>patterns/library/stored_procedure_creator_1_0/MetaObject.wm</Template>
      <Package>java.$(StoredProcedurePackage.Lower)</Package>
      <FileName>$(StoredProcedure.Upper1)Meta.java</FileName>
      <Override>Merge</Override>
    </Build>

    <Build>
      <Template>patterns/library/stored_procedure_creator_1_0/Resources.wm</Template>
      <Package>java.$(StoredProcedurePackage.Lower)</Package>
      <FileName>$(StoredProcedure.Upper1)Resources.properties</FileName>
      <Override>Merge</Override>
    </Build>
  </Components>
</BuildPattern>
