=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/common_1_0/pattern_1_0.dtd
<?xml version="1.0" encoding="US-ASCII"?>

<!-- This dtd is used for validating the Pattern Templates, utitlised by the Pattern Generator, for generating the various components of a Pattern -->

<!ELEMENT BuildPattern (Name,PreRequesites,Components)>
<!ELEMENT Name (#PCDATA)>

<!ELEMENT PreRequesites (Class*)>
<!ELEMENT Class (#PCDATA)>

<!ELEMENT Components (Build+)>
<!ELEMENT Build (Template,Package,FileName,Override,Generate?)>
<!ELEMENT Template (#PCDATA)>
<!ELEMENT Package (#PCDATA)>
<!ELEMENT FileName (#PCDATA)>
<!ELEMENT Override (#PCDATA)>
<!ELEMENT Generate (Type,ClassName?,Arguments?,WorkingDirectory?,CommandLine?)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT ClassName (#PCDATA)>
<!ELEMENT Arguments (#PCDATA)>
<!ELEMENT WorkingDirectory (#PCDATA)>
<!ELEMENT CommandLine (#PCDATA)>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/object_lookup_1_0/ObjectLookupPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>ObjectLookupPattern</Name>
  
    <PreRequesites>
    </PreRequesites>
    
    
    <Components>
        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentLookupInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)InDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentLookupOutRowDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)OutRowDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentLookupOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)OutDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_lookup_1_0/IComponent.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>I$(Component.Upper1).java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentTx.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).tx</Package>
            <FileName>$(Component.Upper1)Tx.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentController.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Component.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentCriteriaForm.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)CriteriaForm.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentResultsForm.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)ResultsForm.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentCriteriaAction.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)CriteriaAction.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentResultsAction.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)ResultsAction.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentCriteriaJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower).jsp</Package>
            <FileName>criteria.jsp</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentResultsJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower).jsp</Package>
            <FileName>results.jsp</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentDefinitionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentDefinition.xfragment</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentStrutsFormBeanXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigFormBean.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentStrutsGlobalForwardXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigGlobalForward.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_lookup_1_0/ComponentStrutsActionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigAction.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_lookup_1_0/ApplicationResources.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ApplicationResources.properties</FileName>
            <Override>True</Override>
        </Build>
    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/skeleton_component_2_0/SkeletonComponentPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>SkeletonComponentPattern</Name>

    <PreRequesites>
    </PreRequesites>
    
    <Components>
        <Build>
            <Template>patterns/library/skeleton_component_2_0/IComponent.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>I$(Component.Upper1).java</FileName>
            <Override>False</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentTx.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).tx</Package>
            <FileName>$(Component.Upper1)Tx.java</FileName>
            <Override>False</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentController.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Component.java</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentForm.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Form.java</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentAction.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Action.java</FileName>
            <Override>False</Override>
        </Build>


#if ($Screens != null) #begin
#foreach $screen in $Screens.values() #begin
        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower)</Package>
            <FileName>$(screen.ScreenName.Lower1).jsp</FileName>
            <Override>False</Override>
        </Build>

#end
#end
        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentContextNavJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower)</Package>
            <FileName>contextNav.jsp</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentDefaultNavJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower)</Package>
            <FileName>defaultNav.jsp</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentDefinitionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentDefinition.xfragment</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentStrutsFormBeanXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigFormBean.xfragment</FileName>
            <Override>False</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentStrutsGlobalForwardXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigGlobalForward.xfragment</FileName>
            <Override>False</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentStrutsActionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigAction.xfragment</FileName>
            <Override>False</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_2_0/ComponentTilesDefinitions.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentTilesDefinitions.xfragment</FileName>
            <Override>False</Override>
        </Build>
        
        <Build>
            <Template>patterns/library/skeleton_component_2_0/ApplicationResources.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ApplicationResources.properties</FileName>
            <Override>False</Override>
        </Build>
    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/skeleton_component_1_0/SkeletonComponentPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>SkeletonComponentPattern</Name>

    <PreRequesites>
    </PreRequesites>
    
    <Components>
        <Build>
            <Template>patterns/library/skeleton_component_1_0/IComponent.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>I$(Component.Upper1).java</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentTx.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).tx</Package>
            <FileName>$(Component.Upper1)Tx.java</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentController.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Component.java</FileName>
            <Override>True</Override>
        </Build>


#if ($Screens != null) #begin
#foreach $screen in $Screens.values() #begin
#if ($(screen.ScreenName) != null) #begin
#set $wm_form = "$(Component.Upper1)$(screen.ScreenName.Upper1)Form.java"
#else
#set $wm_form = "$(Component.Upper1)Form.java"
#end
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentForm.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$wm_form</FileName>
            <Override>True</Override>
        </Build>

#end
#end


#if ($Screens != null) #begin
#foreach $screen in $Screens.values() #begin
#if ($(screen.ScreenName) != null) #begin
#set $wm_action = "$(Component.Upper1)$(screen.ScreenName.Upper1)Action.java"
#else
#set $wm_action = "$(Component.Upper1)Action.java"
#end
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentAction.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$wm_action</FileName>
            <Override>True</Override>
        </Build>

#end
#end


#if ($Screens != null) #begin
#foreach $screen in $Screens.values() #begin
#if ($(screen.ScreenName) != null) #begin
#set $wm_jsp = "$(screen.ScreenName.Lower1).jsp"
#else
#set $wm_jsp = "default.jsp"
#end
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower).jsp</Package>
            <FileName>$wm_jsp</FileName>
            <Override>True</Override>
        </Build>

#end
#end
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentDefinitionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentDefinition.xfragment</FileName>
            <Override>True</Override>
        </Build>

        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentStrutsFormBeanXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigFormBean.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentStrutsGlobalForwardXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigGlobalForward.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ComponentStrutsActionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigAction.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/skeleton_component_1_0/ApplicationResources.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ApplicationResources.properties</FileName>
            <Override>True</Override>
        </Build>
    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/object_finder_2_1/ObjectFinderPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>ObjectFinderPattern</Name>
  
    <PreRequesites>
    </PreRequesites>
    
    
    <Components>
        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentFinderInDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)InDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentFinderOutRowDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)OutRowDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentFinderOutDto.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).dto</Package>
            <FileName>$(Component.Upper1)OutDto.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_finder_2_1/IComponent.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>I$(Component.Upper1).java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentTx.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).tx</Package>
            <FileName>$(Component.Upper1)Tx.java</FileName>
            <Override>Merge</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentController.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Component.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentForm.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Form.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentAction.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower).ui</Package>
            <FileName>$(Component.Upper1)Action.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentCriteriaJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower)</Package>
            <FileName>criteria.jsp</FileName>
            <Override>OverrideIfMarkerPresentOrCreateTempFileIfMarkerAbsent</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentResultsJSP.wm</Template>
            <Package>html.$(Application.Lower).$(Module.Lower).$(Component.Lower)</Package>
            <FileName>results.jsp</FileName>
            <Override>OverrideIfMarkerPresentOrCreateTempFileIfMarkerAbsent</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentDefinitionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentDefinition.xfragment</FileName>
            <Override>False</Override>
        </Build>

        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentStrutsFormBeanXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigFormBean.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentStrutsGlobalForwardXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigGlobalForward.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentStrutsActionXML.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>StrutsConfigAction.xfragment</FileName>
            <Override>True</Override>
        </Build>
    
        <Build>
            <Template>patterns/library/object_finder_2_1/ComponentTilesDefinitions.wm</Template>
            <Package>java.$(BasePackage.Lower).components.$(Component.Lower)</Package>
            <FileName>ComponentTilesDefinitions.xfragment</FileName>
            <Override>False</Override>
        </Build>
    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/data_security_policy_1_1/SecurityDomainPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>CreatPackagePattern</Name>

    <PreRequesites>
    </PreRequesites>

    <Components>
        <Build>
            <Template>patterns/library/data_security_policy_1_1/CreatePredicate.wm</Template>
            <Package>sql.admin.datasecurity.$(MappingPackage.Lower)</Package>
            <FileName>$(BasePackage)_CreatePredicate.sql</FileName>
            <Override>True</Override>
        </Build>
        <Build>
            <Template>patterns/library/data_security_policy_1_1/DropPredicate.wm</Template>
            <Package>sql.system.datasecurity.$(MappingPackage.Lower)</Package>
            <FileName>$(BasePackage)_DropPredicate.sql</FileName>
            <Override>True</Override>
        </Build>
        <Build>
            <Template>patterns/library/data_security_policy_1_1/ApplyPredicate.wm</Template>
            <Package>sql.system.datasecurity.$(MappingPackage.Lower)</Package>
            <FileName>$(BasePackage)_ApplyPredicate.sql</FileName>
            <Override>True</Override>
        </Build>

    </Components>
</BuildPattern>

=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/domain_for_view_1_0/DomainForViewPattern.xml
<?xml version="1.0"?>
<!DOCTYPE BuildPattern PUBLIC "-//JAFFA//DTD Pattern 1.0//EN" "http://jaffa.sourceforge.net/DTD/pattern_1_0.dtd">

<BuildPattern>
    <Name>DomainForViewPattern</Name>

    <PreRequesites>
    </PreRequesites>

    <Components>
        <Build>
            <Template>patterns/library/domain_for_view_1_0/DomainObjectWithJpa.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1).java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/domain_for_view_1_0/MetaObject.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1)Meta.java</FileName>
            <Override>Merge</Override>
        </Build>

        <Build>
            <Template>patterns/library/domain_for_view_1_0/Resources.wm</Template>
            <Package>java.$(DomainPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1)Resources.properties</FileName>
            <Override>Merge</Override>
        </Build>
        
        <Build>
            <Template>patterns/library/domain_for_view_1_0/Mapping.wm</Template>
            <Package>java.$(MappingPackage.Lower)</Package>
            <FileName>$(DomainObject.Upper1).xml</FileName>
            <Override>True</Override>
        </Build>

    </Components>
</BuildPattern>
