=== jaffa-projects/maven-tools/patterngenerator/src/main/java/jaffatools/patterns/library/domain_creator_1_1/domain-creator-meta_1_1.dtd
<?xml version="1.0" encoding="US-ASCII"?>

<!-- This dtd is used for validating the Meta files for generating the various domain object files  -->

<!ELEMENT Root (DomainObject,DomainPackage,DatabaseTable,DomainInfo?,MappingPackage,PatternTemplate,DeleteDomainObject?,DeleteDomainPackage?,Description?,LabelToken?,FlexDomainInfo?,Lockable?,Distributable?,Fields,Relationships?)>
<!ELEMENT DomainObject (#PCDATA)>
<!ELEMENT DomainPackage (#PCDATA)>
<!ELEMENT DatabaseTable (#PCDATA)>
<!ELEMENT DomainInfo (#PCDATA)> 
<!ELEMENT MappingPackage (#PCDATA)>
<!ELEMENT PatternTemplate (#PCDATA)>
<!ELEMENT DeleteDomainObject (#PCDATA)>
<!ELEMENT DeleteDomainPackage (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT LabelToken (#PCDATA)>
<!ELEMENT FlexDomainInfo (#PCDATA)> <!-- Possible values are true, false -->
<!ELEMENT Lockable (#PCDATA)> <!-- Possible values are true, false -->
<!ELEMENT Distributable (#PCDATA)>

<!ELEMENT Fields (Field+)>
<!ELEMENT Field (Name,DataType,DatabaseFieldName,DatabaseDataType,Rpad?,PrimaryKey?,AutoGenerated?,DatabaseSequence?,Description?,LabelToken?,Mandatory?,Width?,IntSize?,FracSize?,MinValue?,MaxValue?,Layout?,Pattern?,CaseType?,Ignore?,StampType?,Comment?)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT DataType (#PCDATA)>
<!ELEMENT DatabaseFieldName (#PCDATA)>
<!ELEMENT DatabaseDataType (#PCDATA)>
<!ELEMENT Rpad (#PCDATA)>
<!ELEMENT PrimaryKey (#PCDATA)>
<!ELEMENT AutoGenerated (#PCDATA)>
<!ELEMENT DatabaseSequence (#PCDATA)>
<!ELEMENT Mandatory (#PCDATA)>
<!ELEMENT Width (#PCDATA)>
<!ELEMENT IntSize (#PCDATA)>
<!ELEMENT FracSize (#PCDATA)>
<!ELEMENT MinValue (#PCDATA)>
<!ELEMENT MaxValue (#PCDATA)>
<!ELEMENT Layout (#PCDATA)>
<!ELEMENT Pattern (#PCDATA)>
<!ELEMENT CaseType (#PCDATA)>
<!ELEMENT Ignore (#PCDATA)>
<!ELEMENT StampType (#PCDATA)> <!-- Possible values are CreatedUserId, CreatedDateTime, LastUpdatedUserId or LastUpdatedDateTime -->
<!ELEMENT Comment EMPTY>
<!ATTLIST Comment Style (plain|lifo|fifo) "plain" >

<!ELEMENT Relationships (Relationship+)>
<!-- The 'Name', if not specified, will be defaulted to the value of 'ToDomainObject' -->
<!ELEMENT Relationship (Name?,ToDomainObject,ToDomainPackage,FromCardinality,ToCardinality,Type,FromFields,ToFields)>
<!ELEMENT ToDomainObject (#PCDATA)>
<!ELEMENT ToDomainPackage (#PCDATA)>
<!ELEMENT FromCardinality (#PCDATA)>
<!ELEMENT ToCardinality (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT FromFields (RelationshipField+)>
<!ELEMENT ToFields (RelationshipField+)>
<!ELEMENT RelationshipField (Name)>

=== jaffa-projects/maven-tools/patterngenerator/src/test/resources/PurchaseRequestDelete.xml
<?xml version="1.0"?>
<!DOCTYPE Root PUBLIC "-//JAFFA//DTD Domain Creator Meta 1.1//EN" "http://jaffa.sourceforge.net/DTD/domain-creator-meta_1_1.dtd">

<!--
Non-null values for the following elements will be retained, the next time this file is regenerated, provided the merge option is set in the TableInfo file.
1- Table Level: Description, LabelToken
2- Field Level: Description, LabelToken, Layout, Pattern, CaseType, Ignore
-->

<!-- IDEAL Mapping -->
<Root>
  <DomainObject>PurchaseRequestDelete</DomainObject>
  <DomainPackage>com.mirotechnologies.requisitioning.purchase.domain</DomainPackage>
  <DatabaseTable>PURCHASE_REQUESTS_DEL</DatabaseTable>
  <MappingPackage>resources/jdbcengine</MappingPackage>
  <PatternTemplate>patterns/library/domain_creator_1_2/DomainCreatorPattern.xml</PatternTemplate>
  <Description></Description>
  <LabelToken>[label.Requisitioning.Purchase.PurchaseRequestDelete]</LabelToken>
  <Fields>
    <Field>
      <Name>OrderNo</Name>
      <DataType>java.lang.String</DataType>
      <DatabaseFieldName>ORDER_NO</DatabaseFieldName>
      <DatabaseDataType>STRING</DatabaseDataType>
      <PrimaryKey>T</PrimaryKey>
      <LabelToken>[label.Requisitioning.Purchase.PurchaseRequestDelete.OrderNo]</LabelToken>
      <Mandatory>T</Mandatory>
      <IntSize>20</IntSize>
      <Layout></Layout>
      <Pattern></Pattern>
      <CaseType>UpperCase</CaseType>
      <Ignore>false</Ignore>
    </Field>
    <Field>
      <Name>VersionNumber</Name>
      <DataType>java.lang.Long</DataType>
      <DatabaseFieldName>VERSION_NUMBER</DatabaseFieldName>
      <DatabaseDataType>INTEGER</DatabaseDataType>
      <PrimaryKey>F</PrimaryKey>
      <LabelToken>[label.Requisitioning.Purchase.PurchaseRequestDelete.VersionNumber]</LabelToken>
      <Mandatory>F</Mandatory>
      <IntSize>10</IntSize>
      <Layout></Layout>
      <Pattern></Pattern>
      <CaseType>UpperCase</CaseType>
      <Ignore>false</Ignore>
    </Field>
    <Field>
      <Name>DeletionCreatedOn</Name>
      <DataType>org.jaffa.datatypes.DateTime</DataType>
      <DatabaseFieldName>DELETION_CREATED_ON</DatabaseFieldName>
      <DatabaseDataType>DATE_TIME</DatabaseDataType>
      <PrimaryKey>F</PrimaryKey>
      <LabelToken>[label.Requisitioning.Purchase.PurchaseRequestDelete.DeletionCreatedOn]</LabelToken>
      <Mandatory>F</Mandatory>
      <Layout></Layout>
      <Pattern></Pattern>
      <CaseType>UpperCase</CaseType>
      <Ignore>false</Ignore>
      <StampType>CreatedDateTime</StampType>
    </Field>
  </Fields>
</Root>
